In [ ]:
#importing
import numpy as np

In [ ]:
#create an array with 4-rows and 8-columns
a=np.eye(4,8)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [ ]:
c=np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,1,2,3,4],[9,0,1,2,3,4,5,6],[3,4,5,6,9,8,7,1]])
print(c)

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]
 [9 0 1 2 3 4 5 6]
 [3 4 5 6 9 8 7 1]]


In [ ]:
b=np.random.rand(1)
print(b)

[0.20004465]


In [ ]:
d=np.random.rand(8,4) #rand-range is between 0 and 1
print(d)

[[0.78367986 0.23436936 0.57873817 0.19727506]
 [0.53131151 0.37057921 0.48924644 0.14192444]
 [0.09493327 0.28722168 0.57983281 0.01071903]
 [0.75886157 0.91885963 0.15842537 0.13668903]
 [0.28039169 0.05141379 0.08174929 0.24032043]
 [0.4370635  0.3780404  0.81720668 0.71584106]
 [0.55418753 0.95043435 0.74113002 0.82498429]
 [0.02986814 0.79277473 0.13472115 0.25295412]]


In [ ]:
e=np.arange(1,33).reshape(8,4)
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(e,4) #splitting

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(e,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(e,(2,7)) #split 2nd row after 7th row

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [ ]:
#create an array with 4-rows and 8-columns
e=np.arange(1,33).reshape(4,8)
print(e)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(e,4) #using hsplit

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(e,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

Trignometry


In [ ]:
np.pi


3.141592653589793

In [ ]:
a=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(a)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(a)

array([ 45.,  60.,  90., 180.])

In [ ]:
b=[45,60,90,180]
np.deg2rad(b)


array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
#radians
np.sin(1)

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([6,5,4,3,2,1])

In [ ]:
np.mean(st)

3.5

In [ ]:
np.median(st)

3.5

In [ ]:
np.var(st)

2.9166666666666665

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(c))

23


In [ ]:
c=np.arange(1,25).reshape(6,4)
print(np.argmax(c))

23


In [ ]:
d=10*np.random.rand(24).reshape(6,4)
print(d)

[[9.25887726 0.35415062 2.19298553 9.14765204]
 [1.47941281 1.72808555 9.01357148 4.649553  ]
 [2.46193801 4.80525468 1.47261125 0.91434196]
 [2.54748219 5.70676932 4.11823174 0.61435942]
 [4.01068779 7.02276955 5.86749824 5.28702032]
 [4.61919852 3.23961805 3.87815914 9.26595233]]


In [ ]:
print(np.argmax(d))

23


In [ ]:
d=12*np.random.rand(25).reshape(5,5)
print(d)

[[ 6.77444234  0.65784338  7.81291698  4.3491296   3.19527744]
 [ 2.06445704  0.7119661  11.38097255 11.23469618  7.25814891]
 [11.54043494  7.40163869  0.86358506  2.41696534 11.84651985]
 [ 9.34711863  4.70637903  9.02641978  0.74889954 10.46457128]
 [ 8.27235086  1.54389652  0.22846069  5.38326425  5.9404733 ]]


In [ ]:
print(np.argmax(d))

14


In [ ]:
print(np.argmax(d,axis=1))

[2 2 4 4 0]


In [ ]:
print(np.argmax(d,axis=0))

[2 2 1 1 2]


In [ ]:
print(np.argmin(d,axis=1))

[1 1 2 3 2]


In [ ]:
print(np.argmin(d,axis=0))

[1 0 4 3 0]


Searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))


(array([0, 1, 4]),)


In [ ]:
b=np.array([1,2,3,-1,-2,-3])
print(np.where(b>=0))

(array([0, 1, 2]),)


In [ ]:
c=np.array([24,16,7,17,54,60])
print(np.where(c%6==0))

(array([0, 4, 5]),)


In [ ]:
c=np.array([13,14,15,16,19,40])
x=np.searchsorted(c,16)
print(x)

3


Sorting Array

In [ ]:
a=np.array(['kusuma','veena','kaveri'])
print(np.sort(a))

['kaveri' 'kusuma' 'veena']


In [ ]:
a=np.array([True,False,True])
print(np.sort(a))

[False  True  True]


In [ ]:
a=np.array(([5,23,99],[33,6,90])) #2D sort-sorting happens within rows
print(np.sort(a))

[[ 5 23 99]
 [ 6 33 90]]


Array Filter

In [ ]:
a=np.array([22,55,66,99,88,13])
filt=np.where(a%2 == 0)
print(filt)

(array([0, 2, 4]),)


In [ ]:
a[filt]

array([22, 66, 88])

Iterating Through Arrays

In [ ]:
names=np.array(["kusuma","veena","kaveri"])
intials=np.array(["B","J","T"])
for i,j in zip(intials,names):
  print(i,".",j)

B . kusuma
J . veena
T . kaveri


In [ ]:
a=np.array([2,3,4,5,6])
b=np.array([10,20,30,40,50])
n=np.multiply(a,b)
print(n)

[ 20  60 120 200 300]


In [ ]:
a=np.array([2,3,4,5,6])
b=np.array([10,20,30,40,50])
n=np.divide(a,b)
print(n)

[0.2        0.15       0.13333333 0.125      0.12      ]


In [ ]:
a=np.array([2,3,4,5,6])
b=np.array([10,20,30,40,50])
n=np.mod(a,b)
print(n)

[2 3 4 5 6]


In [ ]:
a=np.array([2,3,4,5,6])
b=np.array([10,20,30,40,50])
n=np.divmod(a,b)
print(n)

(array([0, 0, 0, 0, 0]), array([2, 3, 4, 5, 6]))


Logarithms

In [ ]:
a=1.2 #natural log e
print(np.log(a))

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a)) #natural log base 2

0.2630344058337938


In [ ]:
a=1.2 #natural log base 10
print(np.log10(a))

0.07918124604762482


In [ ]:
a=np.array([1,1.2,3,4]) ##natural log using array
print(np.log(a))

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
a=np.array([1,1.2,3,4]) ##natural log with base 2 using array
print(np.log2(a))

[0.         0.26303441 1.5849625  2.        ]


In [ ]:
a=np.array([1,10,3,4])
b=np.cumprod(a)
print(b)

[  1  10  30 120]


In [ ]:
a=np.array([1,10,3,4])
b=np.cumsum(a)
print(b)

[ 1 11 14 18]


In [ ]:
a=np.array([1,10,3,4]) # O:10-1,3-10,4-3
b=np.diff(a)
print(b)

[ 9 -7  1]


In [ ]:
n1=10
n2=20
a=np.lcm(n1,n2)
print(a)

20


In [ ]:
n1=10
n2=20
a=np.gcd(n1,n2)
print(a)

10


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)
print(gc)

3


In [ ]:
a=np.array([12,15,60])
gc=np.lcm.reduce(a)
print(gc)

60
